name: DonationAlert
author: ArkadSt
version: 1.0
main: org.arkadst.donationalert.Main
api-version: 1.16

commands:
  announce:
    description: "DonationAlert provided command."
    usage: "§cUsage: /announce COLOR message"
    permission: donationalert.admin
  donationalert:
    description: "DonationAlert provided command."
    permission: donationalert.admin